Berikut adalah implementasi sederhana dari jaringan saraf tiruan (neural network) menggunakan `numpy` untuk mengenali angka dari gambar yang diinputkan sebagai array. Neural network ini dirancang untuk memproses satu input (misalnya, gambar angka "1") dan menghasilkan prediksi. Model ini mencakup satu lapisan tersembunyi dan lapisan output.

### Langkah-langkah Implementasi:
1. **Input Data**: Gambar angka "1" sebagai array.
2. **Forward Propagation**: Memproses data input melalui lapisan tersembunyi dan lapisan output.
3. **Loss Calculation**: Menghitung error berdasarkan hasil prediksi.
4. **Backpropagation**: Mengupdate bobot berdasarkan error.
5. **Prediksi Akhir**: Menunjukkan hasil prediksi.


### Penjelasan:
1. **Input Data**: Array `image_one` mewakili angka "1" dalam grid 3x3.
2. **Forward Propagation**: Input diteruskan melalui jaringan.
3. **Backpropagation**: Gradien dihitung dan bobot diperbarui untuk meminimalkan error.
4. **Prediksi**: Hasil akhirnya adalah indeks dari elemen tertinggi di output, mewakili digit yang dikenali.

Kode ini akan melatih jaringan untuk memprediksi gambar angka "1". Anda dapat memperluasnya untuk dataset lebih besar seperti MNIST.

In [ ]:
import numpy as np

# Fungsi aktivasi sigmoid dan turunan sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Input data: contoh gambar angka "1" dalam array 3x3
# (1 adalah bagian dari angka, 0 adalah latar belakang)
image_one = np.array([
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0]
]).reshape(9, 1)  # Mengubah input menjadi vektor 9x1

# Label target untuk angka "1" (bisa berupa one-hot encoding, misalnya [0,1,0,0,0,0,0,0,0,0])
target = np.array([[0], [1], [0], [0], [0], [0], [0], [0], [0], [0]])

# Inisialisasi bobot secara acak
np.random.seed(42)
# Bobot untuk lapisan tersembunyi (9 input -> 5 neuron)
# 9 input means array dengan length=9
# 5 neuron means length array yang ada ditiap inputnya

weights_hidden = np.random.rand(9, 5)  
# 10 neuron adalah array dengan length = 10
weights_output = np.random.rand(5, 10)  
# Bobot untuk lapisan output (5 neuron -> 10 output)
print(weights_hidden)
print(weights_output)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]
 [0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998]]
[[0.66252228 0.31171108 0.52006802 0.54671028 0.18485446 0.96958463
  0.77513282 0.93949894 0.89482735 0.59789998]
 [0.92187424 0.0884925  0.19598286 0.04522729 0.32533033 0.38867729
  0.27134903 0.82873751 0.35675333 0.28093451]
 [0.54269608 0.14092422 0.80219698 0.07455064 0.98688694 0.77224477
  0.19871568 0.00552212 0.81546143 0.70685734]
 [0.72900717 0.77127035 0.07404465 0.35846573 0.11586906 0.86310343
  0.62329813 0.33089802 0.06355835 0.31098232]
 [0.32518332 0.72

In [ ]:
# Hiperparameter
learning_rate = 0.1
epochs = 10000

# Training Neural Network
for epoch in range(epochs):
    # Forward propagation
    hidden_layer_input = np.dot(image_one.T, weights_hidden)  # (1x9) x (9x5) -> (1x5)
    hidden_layer_output = sigmoid(hidden_layer_input)         # Aktivasi sigmoid
    
    output_layer_input = np.dot(hidden_layer_output, weights_output)  # (1x5) x (5x10) -> (1x10)
    output = sigmoid(output_layer_input)                              # Aktivasi sigmoid
    
    # Hitung error
    error = target.T - output  # Target aktual vs prediksi
    
    # Backpropagation
    d_output = error * sigmoid_derivative(output)
    error_hidden_layer = d_output.dot(weights_output.T)  # (1x10) x (10x5)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)
    
    # Update bobot
    weights_output += hidden_layer_output.T.dot(d_output) * learning_rate
    weights_hidden += image_one.dot(d_hidden_layer) * learning_rate

    if epoch % 1000 == 0:
        loss = np.mean(np.abs(error))
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

# Prediksi
predicted_output = output
print("Hasil prediksi: ", np.argmax(predicted_output))